--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-web-app
  namespace: gitops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd-app
  template:
    metadata:
      labels:
        app: httpd-app
    spec:
      containers:
        - name: httpd-app
          image: chizzydavid/custom-apache-httpd:latest
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 100m

